EmmetFox:
- id: 1
  texte: La prière modifie les choses. Elle ne change pas Dieu, mais elle vous change,
    vous.
- id: 2
  texte: Ce que vous pensez de vous-même est bien plus important que ce que les autres
    pensent de vous.
- id: 3
  texte: La peur est seulement la foi inversée. Elle est foi dans le mal plutôt que
    dans le bien.
- id: 4
  texte: Vous devenez ce à quoi vous pensez le plus souvent.
- id: 5
  texte: Ne regardez jamais les apparences. Regardez seulement la vérité.
- id: 6
  texte: L'Amour divin me remplit et dissout tout ce qui est en moi qui n'est pas
    comme Lui.
- id: 7
  texte: La loi de l’attraction fonctionne que vous le vouliez ou non. Alors, autant
    attirer consciemment le bien.
- id: 8
  texte: L’obstacle sur votre route est le signal qu’il est temps d’avancer par la
    foi.
- id: 9
  texte: Dieu ne vous juge jamais. Il vous aime. Apprenez à faire pareil avec vous-même.
- id: 10
  texte: Quand vous changez votre pensée, vous changez votre vie.
